config/routes.rb
Rails.application.routes.draw do
  post 'payment/page', to: "payment#create", as: 'payment'
  resources :listings
  resources :profiles
  devise_for :users
  root 'home#page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  # belongs_to :profile
  belongs_to :buyer, class_name: "Profile", optional: true
  belongs_to :seller, class_name: "Profile"
  has_many_attached :pictures

  # Add Validations

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: -1}
  validates :status, presence: true
  validates :location, presence: true
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController


  # This is used to get all listings based on a query
  def index

    @listings = []

    # Check if we only want free items
    free = params[:free]

    # If only Free items then show listing with 0 price.
    if(free == "true" || free == true)

      @listings = Listing.where("price <= ?", 0.0)

    # Else Return search results based on ransack logic
    else

      @q = Listing.ransack(params[:q])
     
      @listings = @q.result

    end

  end
  
  def new
      #If user is login then redirect to the login page
      #else redirect to the sell form page
      if user_signed_in?
        # if user has created a profile, show the sell page , else redirect to creating profile page 
        if current_user.profile
          @listing = Listing.new
        else
          redirect_to new_profile_path
        end
      else
        redirect_to new_user_session_path
      end    
  end

  # Used to perform the action of creating a listing
  def create

    # Create a new one
    @listing = Listing.new(listing_params)
  
    # Set the seller to the profile of the logged in user
    @listing.seller_id = current_user.profile.id

    respond_to do |format|

      # Provided the save worked, show new listing
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end

  end


  # Used to get an individual item and mark as sold
  def show

    # Find single item
    @listing = Listing.find(params[:id])

    # If the checkout was successful
    if params[:checkout] == "success"

      # Mark as sold
      @listing.buyer_id = current_user.profile.id
      @listing.save
    end

  end  

  def edit
    @listing = Listing.find(params[:id])
  end

  # This is the action to perform update on listing
  def update


    respond_to do |format|

      # Find the single listing
      @listing = Listing.find(params[:id])

      # Provided the listing seller is the same as logged in user
      if current_user.profile == @listing.seller

        # Update the record
        @listing = Listing.update(params[:id],listing_params)
        if @listing
          format.html { redirect_to @listing, notice: "Listing was successfully updated." }
          format.json { render :show, status: :ok, location: @listing }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end

        # Otherwise return a 401 unauthorized
      else
        format.html { render :edit, status: :unauthorized }
        format.json { render json: @listing.errors, status: :unauthorized }
      end
    end

  end  

  # Used to delete the listing
  def destroy

    respond_to do |format|

      # Get individual listing
      @listing = Listing.find(params[:id])

      # Profiled the current user is the same as the seller
      if current_user.profile == @listing.seller

        # Delete the single record
        @listing = Listing.destroy(params[:id])
        if @listing
          format.html { redirect_to @listing, notice: "Listing was successfully destroyed." }
          format.json { render :show, status: :ok, location: @listing }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
        # Otherwise return 401 unauthorized
      else
        format.html { render :edit, status: :unauthorized }
        format.json { render json: @listing.errors, status: :unauthorized }        
      end
    end

  end

  
  # Here we apply generic filters for acceptable listing fields.
  private

  # Only allow a list of trusted parameters through.
  def listing_params
    params.require(:listing).permit(:title, :description, :price, :status, :location, :create_at, :buyer_id, :seller_id, :profile_id, pictures: [])
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :status %>
    <%= f.input :location %>
    <%= f.file_field :pictures, multiple: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/free.html.erb
<h1>Free </h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>Location</th>
      <% if current_user && current_user.profile %>
      <th>Buyer</th>
      <th>Seller</th>
      <th>Profile</th>
      <%end%>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td>
        <%# Make sure we grab the first image or show default no image placeholder %>
          <% if listing.pictures && listing.pictures.first%>
            <%= image_tag listing.pictures.first, class: "img-thumbnail" %>
          <%else%>
            <%= image_tag "no-img.jpg", class: "img-thumbnail" %>
          <%end%>
        </td>
        <td><%= listing.title %></td>
        <%# Truncate text so it does not overflow... %>
        <td><%= (listing.description).truncate(20) %></td>
        <td>FREE  </td>
        <td><%= listing.status %></td>
        <td><%= listing.location %></td>
        <% if current_user && current_user.profile %>
        <td><%= listing.buyer_id %></td>
        <td><%= listing.seller_id %></td>
        <td><%= listing.profile_id %></td>
        <td><%= link_to 'Show', listing %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.profile %>
<%= link_to 'New Listing', new_listing_path %>
<%end%>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col col-lg-2 col-sm-1">
      
    </div>
    <div class="col col-lg-8 col-sm-10">
      <h1>All Items</h1>

      <%= render 'partials/search' %>

      <table class="table">
        <thead>
          <tr>
            <th>Picture</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Status</th>
            <th>Location</th>
            <% if current_user && current_user.profile %>
            <th>Create at</th>
            <th>Buyer</th>
            <th>Seller</th>
            <th colspan="1"></th>
            <%end%>
          </tr>
        </thead>

        <tbody>
          <% @listings.each do |listing| %>
            <tr>
              <td>
              <%# Grab the first image or show default no image placeholder. %>
                <% if listing.pictures && listing.pictures.first%>
                  <%= image_tag listing.pictures.first, class: "img-thumbnail" %>
                <%else%>
                  <%= image_tag "no-img.jpg", class: "img-thumbnail" %>
                <%end%>
              </td>
              <td><%= listing.title %></td>
              <td><%= 
                # Make sure we limit the description so its does not overflow... 
                (listing.description).truncate(20) %></td>
              <td><%= listing.price %></td>
              <td><%= listing.status %></td>
              <td><%= listing.location %></td>
              <% if current_user && current_user.profile %>
              <td><%= listing.create_at %></td>
              <td><%= listing.buyer_id %></td>
              <td><%= listing.seller_id %></td>
              <td>
                  <%= link_to 'Detail',listing_path(listing), class:"btn btn-success"%>
              </td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <%# Provided the user is logged in show new listing button %>
      <% if current_user && current_user.profile %>
      <%= link_to 'New Listing', new_listing_path %>
      <%end%>

    </div>
    <div class="col col-lg-2 col-sm-1">
      
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-lg-2 col-sm-1">
      
    </div>
    <div class="col col-lg-8 col-sm-10">
    <br />
    <br />
    <br />
        <h1>New Listing</h1>
        <%= render 'form', listing: @listing %>
        <%= link_to 'Back', listings_path %>
    </div>
    <div class="col col-lg-2 col-sm-1">
      
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-lg-2 col-sm-1">
      
    </div>
    <div class="col col-lg-8 col-sm-10">
    <br />
    <br />
    <br />
<p id="notice"><%= notice %></p>

<% if @listing.pictures && @listing.pictures.first%>
  <% @listing.pictures.each do |picture|%>
    <%= image_tag picture, style: "max-width: 180px"%>
  <% end %>
<% else %>
  <%= image_tag "no-img.jpg", style: "max-width: 180px"%>                               
<% end %> 



<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @listing.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @listing.location %>
</p>

  <%# If the item has been sold %>
  <% if @listing.buyer%>  
    <button class="btn btn-danger">Sold</button>
  <%# Otherwise it is still available %>
  <%else%>
    <%# If the logged in user is not the seller and this item has a price %>
    <%if @listing.price != nil && @listing.price > 0 && current_user.id != @listing.seller.id%>
      <%= link_to 'buy', payment_path(listing_id: @listing.id), method: :post, class: "btn btn-danger"%>
    <%end%>
  <%end%>

  <%# If the logged in user is the seller, then let them Edit and Delete the item %>
  <% if current_user && @listing.seller_id == current_user.profile.id%>
    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-warning" %>
    <%= link_to 'Delete', @listing, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>

  <%# Everyone gets to go back in time.... :) %>
  <%= link_to 'Back', listings_path, class: "btn btn-primary" %>
    </div>
    <div class="col col-lg-2 col-sm-1">
      
    </div>
  </div>
</div>